// Auto-generated by WZML-X Bot workflow
// Updated when bot starts/stops
window.tunnelStatus = {
  "status": "offline",
  "url": "",
  "updated": "2026-08-18T16:00:00Z",
  "message": "Bot has not been started yet. Trigger the WZML-X Bot workflow on GitHub Actions."
};
